CREATE TABLE "CLOCK_GENERATION" 
(
    "ID" SERIAL PRIMARY KEY,
    "Product (WPN)"	VARCHAR(512),
    "Datasheet"	VARCHAR(512),
    "OPN"	VARCHAR(512),
    "Price"	FLOAT,
    "Description"	VARCHAR(512),
    "Input Interface Logic"	VARCHAR(512),
    "Output Interface Logic"	VARCHAR(512),
    "fout Typ (MHz)"	FLOAT,
    "fin Typ (MHz)"	FLOAT,
    "VCC Typ (V)"	FLOAT,
    "Package Type"	VARCHAR(512),
    "tJitter(Cy-Cy) Typ (ps)"	INT,
    "tJitter(Period) Typ (ps)"	FLOAT,
    "tJitter(&#934;) Typ (ps)"	FLOAT,
    "tR & tF Typ (ps)"	INT,
    "tR & tF Max (ps)"	INT,
    "TA Min (°C)"	INT,
    "TA Max (°C)"	INT,
    "Qualification"	VARCHAR(512),
    "AEC Qualified"	BOOLEAN,
    "PPAP Capable"	BOOLEAN,
    "Halide Free"	BOOLEAN,
    "Lead Free"	BOOLEAN,
    "Status"	VARCHAR(512)
);

INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3H60113GH3', 'https://www.onsemi.com/download/data-sheet/pdf/NB3H60113GH3-D.PDF', 'NB3H60113GH3MTR2G', null, '2.5 V Programmable OmniClock Generator with Differential LVDS Output. ', 'LVCMOS', 'LVDS', '125', '25', '2.5', 'WDFN-8', '100', '100', '0', '400', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBA3N5573', 'https://www.onsemi.com/download/data-sheet/pdf/NBA3N5573-D.PDF', 'NBA3N5573MNTXG', null, 'PCIe Clock Generator, Automotive Grade, Dual Output, 3.3 V', 'Crystal, LVCMOS', 'HCSL', '200', '25', '3.63', 'QFNW-16', '2', '1.5', '0.4', '340', '700', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3H5150-01', 'https://www.onsemi.com/download/data-sheet/pdf/NB3H5150-01-D.PDF', 'NB3H5150-01MNTXG', null, 'Clock Generator, Multi-Rate, Low Noise 2.5V / 3.3V', 'Crystal, HCSL, LVCMOS, LVDS, LVPECL, TTL', 'LVCMOS, LVPECL', '250', '25', '3.3', 'QFN-32', null, null, '0.5', '800', '1000', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3H5150', 'https://www.onsemi.com/download/data-sheet/pdf/NB3H5150-D.PDF', 'NB3H5150MNTXG', null, 'Clock Generator, Multi-Rate, Low Noise 2.5V / 3.3V', 'Crystal, HCSL, LVDS, LVPECL, TTL', 'LVCMOS, LVPECL', '250', '25', '3.3', 'QFN-32', null, null, '0.5', '800', '1000', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51054', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51054-D.PDF', 'NB3N51054DTR2G', null, 'Quad HCSL/ LVDS Clock Generator, 3.3 V, Crystal to 100 MHz', 'CMOS, Crystal', 'HCSL, LVDS', '100', '25', '3.3', 'TSSOP-24', '20', null, '0.5', null, null, '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51032', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51032-D.PDF', 'NB3N51032DTG', null, 'Clock Generator, 3.3 V, Crystal to 25 MHz, 100 MHz, 125 MHz and 200 MHz Dual HCSL/LVDS ', 'CMOS, Crystal', 'HCSL, LVDS', '200', '25', '3.3', 'TSSOP-16', '20', '10', '0.4', null, '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51032', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51032-D.PDF', 'NB3N51032DTR2G', null, 'Clock Generator, 3.3 V, Crystal to 25 MHz, 100 MHz, 125 MHz and 200 MHz Dual HCSL/LVDS ', 'CMOS, Crystal', 'HCSL, LVDS', '200', '25', '3.3', 'TSSOP-16', '20', '10', '0.4', null, '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N3020', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N3020-D.PDF', 'NB3N3020DTG', null, 'Clock Multiplier, LVPECL / LVCMOS, Programmable, 3.3 V', 'CML, CMOS, ECL', 'ECL, TTL', '210', '27', '3.3', 'TSSOP-16', '20', '15', null, '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N3020', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N3020-D.PDF', 'NB3N3020DTR2G', null, 'Clock Multiplier, LVPECL / LVCMOS, Programmable, 3.3 V', 'CML, CMOS, ECL', 'ECL, TTL', '210', '27', '3.3', 'TSSOP-16', '20', '15', null, '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51044', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51044-D.PDF', 'NB3N51044DTR2G', null, 'Clock Generator, 3.3 V, Crystal to 100 MHz / 125MHz, Quad HCSL / LVDS ', 'CMOS, Crystal', 'HCSL, LVDS', '125', '25', '3.3', 'TSSOP-28', '20', null, '0.4', null, null, '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51034', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51034-D.PDF', 'NB3N51034DTG', null, 'Quad HCSL/LVDS Clock Generator, 3.3 V, Crystal to 100 MHz / 200 MHz ', 'CMOS, Crystal', 'HCSL, LVDS', '200', '25', '3.3', 'TSSOP-20', null, null, '0.4', '400', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N51034', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N51034-D.PDF', 'NB3N51034DTR2G', null, 'Quad HCSL/LVDS Clock Generator, 3.3 V, Crystal to 100 MHz / 200 MHz ', 'CMOS, Crystal', 'HCSL, LVDS', '200', '25', '3.3', 'TSSOP-20', null, null, '0.4', '400', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N3002', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N3002-D.PDF', 'NB3N3002DTG', null, 'Clock Generator, PureEdge&trade;, Crystal to 25 MHz, 100 MHz, 125 MHz, 200 MHz, 3.3 V, with Differential HCSL Outputs ', 'CMOS, TTL', 'HCSL', '200', '25', '3.465', 'TSSOP-16', '2', '1.5', '0.25', '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N3002', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N3002-D.PDF', 'NB3N3002DTR2G', null, 'Clock Generator, PureEdge&trade;, Crystal to 25 MHz, 100 MHz, 125 MHz, 200 MHz, 3.3 V, with Differential HCSL Outputs ', 'CMOS, TTL', 'HCSL', '200', '25', '3.465', 'TSSOP-16', '2', '1.5', '0.25', '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N5573', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N5573-D.PDF', 'NB3N5573DTG', null, 'Clock Generator, Crystal to 25 MHz, 100 MHz, 125 MHz, 200 MHz, 3.3 V, with Dual HCSL', 'Crystal, LVCMOS', 'HCSL', '200', '25', '3.63', 'TSSOP-16', '2', '1.5', '0.4', '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N5573', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N5573-D.PDF', 'NB3N5573DTR2G', null, 'Clock Generator, Crystal to 25 MHz, 100 MHz, 125 MHz, 200 MHz, 3.3 V, with Dual HCSL', 'Crystal, LVCMOS', 'HCSL', '200', '25', '3.63', 'TSSOP-16', '2', '1.5', '0.4', '340', '700', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB4N441', 'https://www.onsemi.com/download/data-sheet/pdf/NB4N441-D.PDF', 'NB4N441MNG', null, 'PLL Clock Synthesizer, Multiprotocol, 3.3 V Serial Input, with Differential LVPECL Output', 'CMOS', 'CMOS', '425', '50', '3.3', 'QFN-24', null, '25', null, '300', '425', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB4N507A', 'https://www.onsemi.com/download/data-sheet/pdf/NB4N507A-D.PDF', 'NB4N507ADR2G', null, 'PECL Clock Synthesizer, 3.3 V / 5 V, 50 - 200 MHz', 'CMOS, TTL', 'ECL', '200', '52', '5', 'SOIC-16', null, '20', null, '270', '500', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N502', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N502-D.PDF', 'NB3N502DR2G', null, 'PLL Clock Multiplier, 14 MHz - 190 MHz, 3.3 V / 5.0 V', 'CMOS, Crystal', 'CMOS', '190', '50', '5.5', 'SOIC-8', '40', '15', null, '1000', '1000', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N502', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N502-D.PDF', 'NB3N502DG', null, 'PLL Clock Multiplier, 14 MHz - 190 MHz, 3.3 V / 5.0 V', 'CMOS, Crystal', 'CMOS', '190', '50', '5.5', 'SOIC-8', '40', '15', null, '1000', '1000', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3H60113GH4', 'https://www.onsemi.com/download/data-sheet/pdf/NB3H60113GH4-D.PDF', 'NB3H60113GH4MTR2G', null, '3.3 V Programmable OmniClock Generator with Single Ended LVCMOS Output', null, null, '39.6', '19.8', null, 'WDFN-8', null, null, null, null, null, '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12429', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12429-D.PDF', 'NBC12429AMNR4G', null, 'PLL Synthesized Clock Generator, Programmable, 3.3 V / 5.0 V (25 to 400 MHz)', 'CMOS', 'ECL', '400', '20', '5', 'QFN-32', null, '25', '20', '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12429', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12429-D.PDF', 'NBC12429FAG', null, 'PLL Synthesized Clock Generator, Programmable, 3.3 V / 5.0 V (25 to 400 MHz)', 'CMOS', 'ECL', '400', '20', '5', 'LQFP-32', null, '25', '20', '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12429', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12429-D.PDF', 'NBC12429FAR2G', null, 'PLL Synthesized Clock Generator, Programmable, 3.3 V / 5.0 V (25 to 400 MHz)', 'CMOS', 'ECL', '400', '20', '5', 'LQFP-32', null, '25', '20', '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12439', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12439-D.PDF', 'NBC12439AMNG', null, 'PLL Clock Generator, Synthesized, Programmable, 3.3 V / 5.0 V, with Power Down (50 to 800 MHz)', 'CMOS', 'ECL', '800', '20', '5', 'QFN-32', '20', '5', null, '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12430', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12430-D.PDF', 'NBC12430AMNG', null, 'PLL Synthesized Clock Generator, Programmable, 3.3 V / 5.0 V (50 to 800 MHz)', 'CMOS', 'ECL', '800', '100', '5', 'QFN-32', '20', '5', null, '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NBC12430', 'https://www.onsemi.com/download/data-sheet/pdf/NBC12430-D.PDF', 'NBC12430FAR2G', null, 'PLL Synthesized Clock Generator, Programmable, 3.3 V / 5.0 V (50 to 800 MHz)', 'CMOS', 'ECL', '800', '100', '5', 'LQFP-32', '20', '5', null, '175', '425', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3H60113GH2', 'https://www.onsemi.com/download/data-sheet/pdf/NB3H60113GH2-D.PDF', 'NB3H60113GH2MTR2G', null, '3.3 V OmniClock Generator with Single Ended LVCMOS Output', null, null, '100', '100', null, 'WDFN-8', null, null, null, null, null, '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N1900K', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N1900K-D.PDF', 'NB3N1900KMNTWG', null, '3.3 V 100/133 MHz Differential 1:19 HCSL Clock ZDB/Fanout Buffer for PCIe', 'HCSL', 'HCSL', null, null, null, 'QFN-72', null, null, null, null, null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N1900K', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N1900K-D.PDF', 'NB3N1900KMNG', null, '3.3 V 100/133 MHz Differential 1:19 HCSL Clock ZDB/Fanout Buffer for PCIe', 'HCSL', 'HCSL', null, null, null, 'QFN-72', null, null, null, null, null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "CLOCK_GENERATION" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Input Interface Logic", "Output Interface Logic", "fout Typ (MHz)", "fin Typ (MHz)", "VCC Typ (V)", "Package Type", "tJitter(Cy-Cy) Typ (ps)", "tJitter(Period) Typ (ps)", "tJitter(&#934;) Typ (ps)", "tR & tF Typ (ps)", "tR & tF Max (ps)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NB3N1900K', 'https://www.onsemi.com/download/data-sheet/pdf/NB3N1900K-D.PDF', 'NB3N1900KMNTXG', null, '3.3 V 100/133 MHz Differential 1:19 HCSL Clock ZDB/Fanout Buffer for PCIe', 'HCSL', 'HCSL', null, null, null, 'QFN-72', null, null, null, null, null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
