CREATE TABLE "COMPARATOR"
(
    "ID" SERIAL PRIMARY KEY,
    "Product (WPN)" VARCHAR(512),
    "Datasheet" VARCHAR(512),
    "OPN" VARCHAR(512),
    "Price" FLOAT,
    "Description" VARCHAR(512),
    "tres Typ (ns)" FLOAT,
    "VCC Min (V)" FLOAT,
    "VCC Max (V)" FLOAT,
    "VIO Max (mV)" FLOAT,
    "ICC Typ (mA)" FLOAT,
    "Number of Channels" INT,
    "Package Type" VARCHAR(512),
    "IO Typ (mA)" FLOAT,
    "TA Min (°C)" INT,
    "TA Max (°C)" INT,
    "Qualification" VARCHAR(512),
    "AEC Qualified" BOOLEAN,
    "PPAP Capable" BOOLEAN,
    "Halide Free" BOOLEAN,
    "Lead Free" BOOLEAN,
    "Status" VARCHAR(512)
);

INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2252', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCV2252SQ2T2G', '0.25', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Open Drain', '50', '1.8', '5.5', '6', '0.15', '1', 'SC-88A / SC-70-5', '50', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2252', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCV2252SN2T1G', '0.28', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Open Drain', '50', '1.8', '5.5', '6', '0.15', '1', 'TSOP-5 / SOT-23-5', '50', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2250', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCV2250SN2T1G', '0.19', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Push-Pull', '50', '1.8', '5.5', '6', '0.15', '1', 'TSOP-5 / SOT-23-5', '50', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2250', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCV2250SQ2T2G', '0.20', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Push-Pull', '50', '1.8', '5.5', '6', '0.15', '1', 'SC-88A / SC-70-5', '50', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV331', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'NCV331SN3T1G', '0.15', 'Comparator, Single, Low Voltage', '800', '2.7', '5', '9', '0.06', '1', 'TSOP-5 / SOT-23-5', '84', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV2393', 'https://www.onsemi.com/download/data-sheet/pdf/NCV2393-D.PDF', 'NCV2393DR2G', '0.31', 'Comparator, Dual, CMOS, 16 V Supply', '1000', '2.7', '16', '14', '0.006', '2', 'SOIC-8', '20', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200A', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCV2200AMUTBG', '0.29', 'Comparator, Complementary, Low Voltage', '1100', '0.85', '6', '5', '0.01', '1', 'UDFN-6', '60', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('TL331', 'https://www.onsemi.com/download/data-sheet/pdf/TL331-D.PDF', 'TL331SN4T1G', '0.07', 'Comparator, Single Channel, Open Collector, Low Power, Wide Supply Range', '400', '2', '36', '9', '0.5', '1', 'TSOP-5 / SOT-23-5', '16', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS3402', 'https://www.onsemi.com/download/data-sheet/pdf/NCS3402-D.PDF', 'NCS3402DR2G', '0.29', 'Comparator, Dual, Low Power', '5000', '2.7', '16', '3.6', '0.00047', '2', 'SOIC-8', '0.5', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FAN156', 'https://www.onsemi.com/download/data-sheet/pdf/FAN156-D.PDF', 'FAN156L6X', '0.18', 'Comparator, Low Voltage', '400', '1.6', '5.5', '15', '0.0055', '1', 'SIP-6', '30', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCV2202SN2T1G', '0.27', 'Comparator, Low Voltage, Open Drain', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202A', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2202AMUTBG', '0.16', 'Comparator, Low Voltage, Open Drain', '580', '0.85', '6', '12', '0.008', '1', 'UDFN-6', '10', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCV2200SN1T1G', '0.21', 'Comparator, Complementary, Low Voltage', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCV2200SQ2T2G', '0.34', 'Comparator, Complementary, Low Voltage', '1100', '0.85', '6', '5', '0.01', '1', 'SC-88A / SC-70-5', '70', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCV2200SN2T1G', '0.38', 'Comparator, Complementary, Low Voltage', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2252', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCS2252SQ2T2G', '0.16', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Open Drain', '50', '1.8', '5.5', '6', '0.15', '1', 'SC-88A / SC-70-5', '50', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2252', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCS2252SN2T1G', '0.19', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Open Drain', '50', '1.8', '5.5', '6', '0.15', '1', 'TSOP-5 / SOT-23-5', '50', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2250', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCS2250SQ2T2G', '0.18', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Push-Pull', '50', '1.8', '5.5', '6', '0.15', '1', 'SC-88A / SC-70-5', '50', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2250', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2250-D.PDF', 'NCS2250SN2T1G', '0.16', 'Comparator, High Speed, 50 ns, Low Voltage, Rail-to-Rail, Push-Pull', '50', '1.8', '5.5', '6', '0.15', '1', 'TSOP-5 / SOT-23-5', '50', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('TL331', 'https://www.onsemi.com/download/data-sheet/pdf/TL331-D.PDF', 'TL331VSN4T1G', null, 'Comparator, Single Channel, Open Collector, Low Power, Wide Supply Range', '400', '2', '36', '9', '0.5', '1', 'TSOP-5 / SOT-23-5', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV331', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV331SQ3T2G', '0.12', 'Comparator, Single, Low Voltage', '800', '2.7', '5', '9', '0.06', '1', 'SC-88A / SC-70-5', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV331', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV331SN3T1G', '0.17', 'Comparator, Single, Low Voltage', '800', '2.7', '5', '9', '0.06', '1', 'TSOP-5 / SOT-23-5', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MC3302', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'MC3302DR2G', '0.21', 'Comparator, Quad, Single Supply', '1300', '3', '30', '20', '1', '4', 'SOIC-14', '16', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('TS393', 'https://www.onsemi.com/download/data-sheet/pdf/NCV2393-D.PDF', 'TS393DR2G', '0.25', 'Comparator, Dual, CMOS, 16 V Supply', '1000', '2.7', '16', '14', '0.006', '2', 'SOIC-8', '20', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV393', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV393DMR2G', '0.16', 'Comparator, Dual, Low Voltage', '800', '2.7', '5.5', '9', '0.1', '2', 'Micro8', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV393', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV393DR2G', '0.26', 'Comparator, Dual, Low Voltage', '800', '2.7', '5.5', '9', '0.1', '2', 'SOIC-8', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV339', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV339DTBR2G', '0.19', 'Comparator, Quad, Low Voltage', '800', '2.7', '5', '9', '0.17', '4', 'TSSOP-14', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV393', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV393MUTAG', '0.47', 'Comparator, Dual, Low Voltage', '800', '2.7', '5.5', '9', '0.1', '2', 'UDFN-8', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LMV339', 'https://www.onsemi.com/download/data-sheet/pdf/LMV331-D.PDF', 'LMV339DR2G', '0.27', 'Comparator, Quad, Low Voltage', '800', '2.7', '5', '9', '0.17', '4', 'SOIC-14', '84', '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('TS391', 'https://www.onsemi.com/download/data-sheet/pdf/TS391-D.PDF', 'NCV391SN2T1G', '0.22', 'Comparator, Single, Low Power, 36 V, Pinout Style: 2', '400', '2', '36', '5', '0.5', '1', 'TSOP-5 / SOT-23-5', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'NCV2901DR2G', '0.13', 'Comparator, Quad, Single Supply, 36V', '1300', '3', '36', '7', '1', '4', 'SOIC-14', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'NCV2901DTBR2G', '0.20', 'Comparator, Quad, Single Supply, 36V', '1300', '3', '36', '7', '1', '4', 'TSSOP-14', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2220', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2220A-D.PDF', 'NCS2220AMUT1G', '0.38', 'Comparator, Dual, Low Voltage', '500', '0.85', '6', '5', '0.0075', '2', 'UDFN-8', '60', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV2903', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'NCV2903DR2G', '0.09', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.7', '2', 'SOIC-8', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV2903', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'NCV2903DMR2G', '0.13', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.7', '2', 'Micro8', '16', '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2202SQ2T2G', '0.14', 'Comparator, Low Voltage, Open Drain, Pinout Style: 2', '1100', '0.85', '6', '5', '0.01', '1', 'SC-88A / SC-70-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200A', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2200AMUT1G', '0.14', 'Comparator, Complementary, Low Voltage', '1100', '0.85', '6', '5', '0.01', '1', 'UDFN-6', '60', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2200SQ2T2G', '0.24', 'Comparator, Complementary, Low Voltage, Pinout Style: 2', '1100', '0.85', '6', '5', '0.01', '1', 'SC-88A / SC-70-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2202SQ1T2G', '0.30', 'Comparator, Low Voltage, Open Drain, Pinout Style: 1', '1100', '0.85', '6', '5', '0.01', '1', 'SC-88A / SC-70-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2200SN2T1G', '0.33', 'Comparator, Complementary, Low Voltage, Pinout Style: 2', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2202SN1T1G', '0.36', 'Comparator, Low Voltage, Open Drain, Pinout Style: 1', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2202', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2202SN2T1G', '0.44', 'Comparator, Low Voltage, Open Drain, Pinout Style: 2', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2200', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2200-D.PDF', 'NCS2200SN1T1G', '0.45', 'Comparator, Complementary, Low Voltage, Pinout Style: 1', '1100', '0.85', '6', '5', '0.01', '1', 'TSOP-5 / SOT-23-5', '70', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM211', 'https://www.onsemi.com/download/data-sheet/pdf/LM211-D.PDF', 'LM211DR2G', '0.17', 'Comparator, Single', '200', '5', '36', '3', '2.4', '1', 'SOIC-8', '8', '-25', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM2901EDR2G', '0.13', 'Comparator, Quad, Single Supply, 36 V', '300', '3', '36', '7', '1', '4', 'SOIC-14', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM311', 'https://www.onsemi.com/download/data-sheet/pdf/LM211-D.PDF', 'LM311DR2G', '0.13', 'Comparator, Single', '200', '5', '36', '7.5', '2.4', '1', 'SOIC-8', '8', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2903', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM2903EDR2G', '0.08', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.4', '2', 'SOIC-8', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NE521', 'https://www.onsemi.com/download/data-sheet/pdf/NE521-D.PDF', 'NE521DR2G', '4.06', 'Dual Differential Comparator/Sense Amp', '9.6', '-7', '7', '7.5', '27', '2', 'SOIC-14', '100', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('TS391', 'https://www.onsemi.com/download/data-sheet/pdf/TS391-D.PDF', 'TS391SN2T1G', '0.20', 'Comparator, Single, Low Power, 36 V, Pinout Style: 2', '400', '2', '36', '5', '0.5', '1', 'TSOP-5 / SOT-23-5', '16', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM2901DR2G', '0.11', 'Comparator, Quad, Single Supply, 36 V, T<sub>A</sub>= -40° to +105°C', '1300', '3', '36', '7', '1', '4', 'SOIC-14', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM2901VDR2G', '0.14', 'Comparator, Quad, Single Supply, 36 V, T<sub>A</sub>= -40° to +125°C', '1300', '3', '36', '7', '1', '4', 'SOIC-14', '16', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM2901VDTBR2G', '0.20', 'Comparator, Quad, Single Supply, 36 V, T<sub>A</sub>= -40° to +125°C', '1300', '3', '36', '7', '1', '4', 'TSSOP-14', '16', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2901', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM2901DTBR2G', '0.20', 'Comparator, Quad, Single Supply, 36 V, T<sub>A</sub>= -40° to +105°C', '1300', '3', '36', '7', '1', '4', 'TSSOP-14', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM239', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM239DR2G', '0.13', 'Comparator, Quad, Single Supply, 36 V', '1300', '3', '36', '5', '1', '4', 'SOIC-14', '16', '-25', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2903', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM2903DR2G', '0.08', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.7', '2', 'SOIC-8', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM239', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM239DTBR2G', '0.19', 'Comparator, Quad, Single Supply, 36 V', '1300', '3', '36', '5', '1', '4', 'TSSOP-14', '16', '-25', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2903', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM2903DMR2G', '0.11', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.7', '2', 'Micro8', '16', '-40', '105', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM2903V', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM2903VDR2G', '0.13', 'Comparator, Dual, Low Offset Voltage', '1500', '2', '36', '7', '0.7', '2', 'SOIC-8', '16', '-40', '125', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM293', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM293DR2G', '0.08', 'Comparator, Dual, Low Offset Voltage', '1300', '2', '36', '5', '0.7', '2', 'SOIC-8', '16', '-25', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM293', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM293DMR2G', '0.14', 'Comparator, Dual, Low Offset Voltage', '1300', '2', '36', '5', '0.7', '2', 'Micro8', '16', '-25', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM393', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM393EDR2G', '0.08', 'Comparator, Dual, Low Offset Voltage', '1300', '2', '36', '5', '0.4', '2', 'SOIC-8', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM339', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM339EDR2G', '0.27', 'Comparator, Quad, Single Supply', '1300', '3', '36', '5', '1', '4', 'SOIC-14', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM339', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM339DR2G', '0.11', 'Comparator, Quad, Single Supply', '1300', '3', '36', '5', '1', '4', 'SOIC-14', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM339', 'https://www.onsemi.com/download/data-sheet/pdf/LM339-D.PDF', 'LM339DTBR2G', '0.20', 'Comparator, Quad, Single Supply', '1300', '3', '36', '5', '1', '4', 'TSSOP-14', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM393', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM393DR2G', '0.09', 'Comparator, Dual, Low Offset Voltage', '1300', '2', '36', '5', '0.7', '2', 'SOIC-8', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('LM393', 'https://www.onsemi.com/download/data-sheet/pdf/LM393-D.PDF', 'LM393DMR2G', '0.10', 'Comparator, Dual, Low Offset Voltage', '1300', '2', '36', '5', '0.7', '2', 'Micro8', '16', '0', '70', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCS2300', 'https://www.onsemi.com/download/data-sheet/pdf/NCS2300-D.PDF', 'NCS2300MUTAG', '0.34', 'Headset Detection Interface', '480', '1.6', '2.5', null, '7.5', '1', 'UDFN-6', null, '-40', '85', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "COMPARATOR" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "tres Typ (ns)", "VCC Min (V)", "VCC Max (V)", "VIO Max (mV)", "ICC Typ (mA)", "Number of Channels", "Package Type", "IO Typ (mA)", "TA Min (°C)", "TA Max (°C)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV1124', 'https://www.onsemi.com/download/data-sheet/pdf/NCV1124 DATA SHEET.PDF', 'NCV1124DR2G', '1.04', 'Comparator, Dual, Variable-Reluctance Sensor Interface', null, '4.5', '5.5', null, null, '2', 'SOIC-8', null, '-40', '125', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
