CREATE TABLE "RF_BJT"
(
    "ID" SERIAL PRIMARY KEY,
    "Product (WPN)" VARCHAR(512),
    "Datasheet" VARCHAR(512),
    "OPN" VARCHAR(512),
    "Price" FLOAT,
    "Description" VARCHAR(512),
    "VCEO Min (V)" FLOAT,
    "fT Min (MHz)" INT,
    "IC Continuous (A)" FLOAT,
    "hFE Min" INT,
    "Polarity" VARCHAR(512),
    "Package Type" VARCHAR(512),
    "PTM Max (W)" FLOAT,
    "|S21e|2 Typ. (dB)" FLOAT,
    "NF Typ. (dB)" FLOAT,
    "hFE Max" INT,
    "Qualification" VARCHAR(512),
    "AEC Qualified" BOOLEAN,
    "PPAP Capable" BOOLEAN,
    "Halide Free" BOOLEAN,
    "Lead Free" BOOLEAN,
    "Status" VARCHAR(512)
);

INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVMMBTH81', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH81-D.PDF', 'NSVMMBTH81LT1G', '0.09', '50 mA, 20 V PNP RF Bipolar Junction Transistor, AEC-Q101 Qualified', '20', '600', '0.05', '60', 'PNP', 'SOT-23-3', '0.225', null, null, null, 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVMMBTH81', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH81-D.PDF', 'NSVMMBTH81LT3G', '0.09', '50 mA, 20 V PNP RF Bipolar Junction Transistor, AEC-Q101 Qualified', '20', '600', '0.05', '60', 'PNP', 'SOT-23-3', '0.225', null, null, null, 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF4009SG4', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF4009SG4-D.PDF', 'NSVF4009SG4T1G', '0.13', 'RF Transistor for Low Noise Amplifier', '3.5', '20000', '0.04', '50', 'NPN', 'SC-82FL / MCPH-4', '0.12', '13.5', '1.1', '120', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBT918L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBT918LT1-D.PDF', 'MMBT918LT1G', '0.03', 'NPN Bipolar Transistor', '15', '600', '0.05', '20', 'NPN', 'SOT-23-3', '0.3', null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MCH4009', 'https://www.onsemi.com/download/data-sheet/pdf/ENA0389-D.PDF', 'MCH4009-TL-H', '0.16', 'RF Transistor, NPN Single, 3.5 V, 40 mA, f<sub>T</sub> = 25 GHz', '3.5', '20000', '0.04', '50', 'NPN', 'SC-82FL / MCPH-4', '0.12', '13.5', '1.1', '120', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH81', 'https://www.onsemi.com/download/data-sheet/pdf/MPSH81-D.PDF', 'MMBTH81', '0.04', '50 mA, 20 V PNP RF Bipolar Junction Transistor', '20', '600', '0.05', '60', 'PNP', 'SOT-23-3', '0.225', null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('15GN03CA', 'https://www.onsemi.com/download/data-sheet/pdf/ENA1106-D.PDF', '15GN03CA-TB-E', '0.06', 'RF Transistor, NPN Single CP, 10 V, 70 mA, f<sub>T</sub> = 1.5 GHz', '10', '1000', '0.07', '100', 'NPN', 'SC-59-3 / CP-3', '0.2', '13', '1.6', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF5501SK', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF5501SK-D.PDF', 'NSVF5501SKT3G', '0.12', 'RF Transistor for Low Noise Amplifier', '10', '3000', '0.07', '100', 'NPN', 'SOT-623 / SSFP', '0.25', '11', '1.9', '160', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('15GN03MA', 'https://www.onsemi.com/download/data-sheet/pdf/ENA1108-D.PDF', '15GN03MA-TL-E', '0.09', 'RF Transistor, NPN Single, 10 V, 70 mA, f<sub>T</sub> = 1.5 GHz', '10', '1500', '0.07', '100', 'NPN', 'SC-70 / MCP3', '0.4', '13', '1.6', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10LT1-D.PDF', 'NSVMMBTH10LT1G', '0.10', 'NPN Bipolar Transistor', '25', '650', null, '60', 'NPN', 'SOT-23-3', '0.3', null, null, null, 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF5488SK', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF5488SK-D.PDF', 'NSVF5488SKT3G', '0.14', 'RF Transistor for Low Noise Amplifier', '10', '5000', '0.07', '90', 'NPN', 'SOT-623 / SSFP', '0.1', '12', '1', '200', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF6001SB6', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF6001SB6-D.PDF', 'NSVF6001SB6T1G', '0.20', 'RF Transistor, NPN Single, 12 V, 100 mA, f<sub>T</sub> = 6.7 GHz', '12', '5000', '0.1', '90', 'NPN', 'CPH-6', '0.8', '11', '1.1', '180', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF4020SG4', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF4020SG4-D.PDF', 'NSVF4020SG4T1G', '0.17', 'RF Transistor for Low Noise Amplifier', '8', '13000', '0.15', '60', 'NPN', 'SC-82FL / MCPH-4', '0.4', '17.5', '1.2', '150', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10LT1-D.PDF', 'SMMBTH10-4LT3G', '0.08', 'NPN Bipolar Transistor', '25', '800', null, '120', 'NPN', 'SOT-23-3', '0.3', null, null, '240', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF4015SG4', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF4015SG4-D.PDF', 'NSVF4015SG4T1G', '0.15', 'RF Transistor for Low Noise Amplifier', '12', '8000', '0.1', '60', 'NPN', 'SC-82FL / MCPH-4', '0.45', '17', '1.2', '150', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10M3', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10M3-D.PDF', 'MMBTH10M3T5G', '0.03', 'NPN Bipolar Transistor', '25', '650', null, '60', 'NPN', 'SOT-723-3', '0.64', null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('55GN01FA', 'https://www.onsemi.com/download/data-sheet/pdf/55GN01FA-D.PDF', '55GN01FA-TL-H', '0.11', 'RF Transistor, NPN Single, 10 V, 70 mA, f<sub>T</sub> = 5.5 GHz', '10', '3000', '0.07', '100', 'NPN', 'SOT-623 / SSFP', '0.25', '11', '1.9', '160', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10LT1-D.PDF', 'MMBTH10LT3G', '0.03', 'NPN Bipolar Transistor, h<sub>FE</sub> ≥ 60; f<sub>T</sub> ≥ 650 MHz', '25', '650', null, '60', 'NPN', 'SOT-23-3', '0.3', null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10LT1-D.PDF', 'MMBTH10LT1G', '0.03', 'NPN Bipolar Transistor, h<sub>FE</sub> ≥ 60; f<sub>T</sub> ≥ 650 MHz', '25', '650', null, '60', 'NPN', 'SOT-23-3', '0.3', null, null, null, 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('55GN01CA', 'https://www.onsemi.com/download/data-sheet/pdf/55GN01CA-D.PDF', '55GN01CA-TB-E', '0.06', 'RF Transistor, NPN Single, 10 V, 70 mA, f<sub>T</sub> = 5.5 GHz', '10', '3000', '0.07', '100', 'NPN', 'SC-59-3 / CP-3', '0.2', '9.5', '1.9', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MMBTH10L', 'https://www.onsemi.com/download/data-sheet/pdf/MMBTH10LT1-D.PDF', 'MMBTH10-4LT1G', '0.03', 'NPN Bipolar Transistor, h<sub>FE</sub> 120 to 240; f<sub>T</sub> ≥ 800 MHz', '25', '800', null, '120', 'NPN', 'SOT-23-3', '0.3', null, null, '240', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NSVF6003SB6', 'https://www.onsemi.com/download/data-sheet/pdf/NSVF6003SB6-D.PDF', 'NSVF6003SB6T1G', '0.20', 'RF Transistor, NPN Single, 12 V, 150 mA, f<sub>T</sub> = 7 GHz', '12', '7000', '0.15', '100', 'NPN', 'CPH-6', '0.8', '9', '1.8', '180', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('2SC5488A', 'https://www.onsemi.com/download/data-sheet/pdf/2SC5488A-D.PDF', '2SC5488A-TL-H', '0.11', 'RF Transistor, NPN Single, 10 V, 70 mA, f<sub>T</sub> = 7 GHz', '10', '5000', '0.07', '90', 'NPN', 'SOT-623 / SSFP', '0.1', '12', '1', '200', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MCH6001', 'https://www.onsemi.com/download/data-sheet/pdf/ENA1601-D.PDF', 'MCH6001-TL-E', '0.21', 'RF Transistor, NPN Dual, 8 V, 150 mA, f<sub>T</sub> = 16 GHz', '8', '13000', '0.15', '60', 'NPN', 'SC-88FL / MCPH-6', '0.6', '16', '1.2', '150', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MCH4020', 'https://www.onsemi.com/download/data-sheet/pdf/ENA1280-D.PDF', 'MCH4020-TL-H', '0.12', 'RF Transistor, NPN Single, 8 V, 150 mA, f<sub>T</sub> = 16 GHz', '8', '13000', '0.15', '60', 'NPN', 'SC-82AB / MCP-4', '0.4', '17.5', '1.2', '150', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('2SC5226A', 'https://www.onsemi.com/download/data-sheet/pdf/2SC5226A-D.PDF', '2SC5226A-4-TL-E', '0.13', 'RF Transistor, NPN Single MCP, 10 V, 70 mA, f<sub>T</sub> = 7 GHz', '10', '7000', '0.07', '90', 'NPN', 'SC-70 / MCP3', '0.15', '12', '1', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('MCH4015', 'https://www.onsemi.com/download/data-sheet/pdf/MCH4015-D.PDF', 'MCH4015-TL-H', '0.12', 'RF Transistor, NPN Single, 12 V, 100 mA, f<sub>T</sub> = 10 GHz', '12', '8000', '0.1', '60', 'NPN', 'SC-82FL / MCPH-4', '0.45', '17', '1.2', '150', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('CPH6001A', 'https://www.onsemi.com/download/data-sheet/pdf/CPH6001A-D.PDF', 'CPH6001A-TL-E', '0.12', 'RF Transistor, 12 V, 100 mA, f<sub>T</sub> = 6.7 GHz', '12', '5000', '0.1', '90', 'NPN', 'CPH-6', '0.8', '11', '1.1', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('2SC5226A', 'https://www.onsemi.com/download/data-sheet/pdf/2SC5226A-D.PDF', '2SC5226A-5-TL-E', '0.10', 'RF Transistor, NPN Single MCP, 10 V, 70 mA, f<sub>T</sub> = 7 GHz', '10', '7000', '0.07', '135', 'NPN', 'SC-70 / MCP3', '0.15', '12', '1', '270', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "RF_BJT" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "VCEO Min (V)", "fT Min (MHz)", "IC Continuous (A)", "hFE Min", "Polarity", "Package Type", "PTM Max (W)", "|S21e|2 Typ. (dB)", "NF Typ. (dB)", "hFE Max", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('CPH6003A', 'https://www.onsemi.com/download/data-sheet/pdf/CPH6003A-D.PDF', 'CPH6003A-TL-E', '0.16', 'RF Transistor, 12 V, 150 mA, f<sub>T</sub> = 7 GHz', '12', '7000', '0.15', '100', 'NPN', 'CPH-6', '0.8', '9', '1.8', '180', 'Standard', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'Active');
