CREATE TABLE "SMART_POWER_STAGE"
(
    "ID" SERIAL PRIMARY KEY,
    "Product (WPN)"	VARCHAR(512),
    "Datasheet"	VARCHAR(512),
    "OPN"	VARCHAR(512),
    "Price"	FLOAT,
    "Description"	VARCHAR(512),
    "Vin Typ (V)"	INT,
    "IO Max (A)"	INT,
    "fSW Max (MHz)"	VARCHAR(512),
    "PWM Level (V)"	VARCHAR(512),
    "Package Type"	VARCHAR(512),
    "Vcc Typ (V)"	INT,
    "Qualification"	VARCHAR(512),
    "AEC Qualified"	BOOLEAN,
    "PPAP Capable"	BOOLEAN,
    "Halide Free"	BOOLEAN,
    "Lead Free"	BOOLEAN,
    "Status"	VARCHAR(512)
);

INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5175', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5175', '1.43', '30A Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '30', '1', '3.3V, 5V', 'PQFN-24', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5075', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5075', '1.40', '20A Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '20', '1', '3.3V, 5V', 'PQFN-24', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5176', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5176', '1.49', '45A Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '45', '1', '3.3V, 5V', 'PQFN-24', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5076', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5076', '1.47', '35A Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '35', '1', '3.3V, 5V', 'PQFN-24', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5049', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5049', '2.47', 'Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '100', '1', '3.3V', 'LQFN34 4x6, 0.45P', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5068', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5068', '1.97', 'Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '70', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5062', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5062', '1.98', 'Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '70', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5085', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5085', '2.07', 'Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '108', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF5071', 'https://www.onsemi.com/download/data-sheet/pdf/null', 'FDMF5071', '1.93', 'Smart Power Stage (SPS) Modules with Integrated Current and Temperature Monitors', '12', '90', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('FDMF6820A', 'https://www.onsemi.com/download/data-sheet/pdf/FDMF6820A-D.PDF', 'FDMF6820A', '1.65', 'Extra-Small, High-Performance, High-Frequency DrMOS Module', '12', '60', '1', '3.3V', 'PQFN-40', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP303160A', 'https://www.onsemi.com/download/data-sheet/pdf/NCP303160A-D.PDF', 'NCP303160AMNTWG', '1.05', 'Integrated Driver and MOSFET with Integrated Current Monitor, 60A', '19', '80', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV303150', 'https://www.onsemi.com/download/data-sheet/pdf/NCV303150-D.PDF', 'NCV303150MTW', '3.28', 'Integrated Driver and MOSFET with Integrated Current Monitor', '19', '50', '1', '3.3V, 5V', 'WQFNW39 5x6, 0.45P', '5', 'Automotive', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP303152', 'https://www.onsemi.com/download/data-sheet/pdf/NCP303152-D.PDF', 'NCP303152MNTWG', '1.89', 'Integrated Driver and MOSFET with Integrated Current Monitor', '19', '50', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP302035', 'https://www.onsemi.com/download/data-sheet/pdf/NCP302035-D.PDF', 'NCP302035MNTWG', '0.87', '35A Integrated Driver and MOSFETs', '19', '35', '1', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP303160', 'https://www.onsemi.com/download/data-sheet/pdf/NCP303160-D.PDF', 'NCP303160MNTWG', '1.88', 'Integrated Driver and MOSFET with Integrated Current Monitor, 60A', '19', '60', '1', '3.3V, 5V', 'PQFN-39', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP252163', 'https://www.onsemi.com/download/data-sheet/pdf/NCP252163-D.PDF', 'NCP252163MNTWG', '1.27', 'Integrated Driver and MOSFET', '12', '60', '2', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP302040', 'https://www.onsemi.com/download/data-sheet/pdf/NCP302040-D.PDF', 'NCP302040MNTWG', '0.89', 'Integrated Driver and MOSFETs, 40 A', '12', '70', '2', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCV3025833', 'https://www.onsemi.com/download/data-sheet/pdf/NCV3025833-D.PDF', 'NCV3025833MTW', null, 'Smart Power Stage (SPS) Module with Integrated Thermal Warning and Thermal Shutdown', '19', '50', '1.5', '5V', 'WQFNW-33', '5', 'Automotive', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP302045', 'https://www.onsemi.com/download/data-sheet/pdf/NCP302045-D.PDF', 'NCP302045MNTWG', '0.93', 'Integrated Driver and MOSFETs, 45 A', '12', '75', '2', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP302155A', 'https://www.onsemi.com/download/data-sheet/pdf/NCP302155A-D.PDF', 'NCP302155AMNTWG', '1.07', 'Integrated Driver and MOSFETs, 55 A', '19', '55', '2', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
INSERT INTO "SMART_POWER_STAGE" ("Product (WPN)", "Datasheet", "OPN", "Price", "Description", "Vin Typ (V)", "IO Max (A)", "fSW Max (MHz)", "PWM Level (V)", "Package Type", "Vcc Typ (V)", "Qualification", "AEC Qualified", "PPAP Capable", "Halide Free", "Lead Free", "Status") VALUES ('NCP302155R', 'https://www.onsemi.com/download/data-sheet/pdf/NCP302155R-D.PDF', 'NCP302155RMNTWG', null, 'Integrated Driver and MOSFET', '20', '55', '2', '3.3V, 5V', 'PQFN-31', '5', 'Standard', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'Active');
