CREATE TABLE "AUDIO_AMPLIFIER" 
(
    "ID" SERIAL PRIMARY KEY,
    "Product Group"	VARCHAR(512),
    "Status"	VARCHAR(512),
    "Compliance"	VARCHAR(512),
    "Class"	VARCHAR(512),
    "Output Power Typ (W)"	FLOAT,
    "VCC Max (V)"	FLOAT,
    "Output Type"	VARCHAR(512),
    "ton Typ (ms)"	FLOAT,
    "THD + N Typ (%)"	FLOAT,
    "IQ Typ (mA)"	FLOAT,
    "ISD Typ (nA)"	FLOAT,
    "Package Type"	VARCHAR(512),
    "MSL Type"	INT,
    "MSL Temp (°C)"	INT,
    "Pricing ($/Unit)"	FLOAT
);

INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('FAB3103UCX', 'Last Shipments', 'Pb H ', 'D', '2.3', null, 'Single', null, '0.02', '2.7', '100', 'WLCSP-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2704FCCT1G', 'Last Shipments', 'Pb', 'D', '1.4', '5.5', 'Differential', '1', '0.1', '3.6', '100', 'Flip-Chip-20', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2809BDMR2G', 'Last Shipments', 'Pb H ', 'AB', '0.135', '5.5', 'Multiple Analog', '285', '0.003', '1.5', '10', 'Micro10', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2809BMUTXG', 'Obsolete', 'Pb H ', 'AB', '0.135', '5.5', 'Multiple Analog', '285', '0.003', '1.5', '10', 'UDFN-10', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2809ADMR2G', 'Obsolete', 'Pb H ', 'AB', '0.135', '5.5', 'Multiple Analog', '285', '0.003', '1.5', '10', 'Micro10', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811ADTBR2G', 'Active, Not Rec', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'TSSOP-14', '1', '260', '0.4593');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811AFCT1G', 'Last Shipments', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'Flip-Chip-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811BFCCT1G', 'Lifetime', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'Flip-Chip-12', '1', '260', '0.3987');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811BDTBR2G', 'Obsolete', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'TSSOP-14', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811AMTTXG', 'Obsolete', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'WQFN-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811BMTTXG', 'Obsolete', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'WQFN-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2811BFCT1G', 'Obsolete', 'Pb H ', 'AB', '0.11', '5', 'Multiple Analog', '1', '0.01', '6', '10', 'Flip-Chip-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2815BFCCT2G', 'Obsolete', 'Pb H ', 'AB', '0.03', '3.6', 'Differential', '1', '0.01', '1.6', '10', 'Flip-Chip-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2815BFCT2G', 'Obsolete', 'Pb H ', 'AB', '0.03', '3.6', 'Differential', '1', '0.01', '1.6', '10', 'Flip-Chip-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2815AFCT2G', 'Obsolete', 'Pb H ', 'AB', '0.03', '3.6', 'Differential', '1', '0.01', '1.6', '10', 'Flip-Chip-12', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2817BFCCT2G', 'Lifetime', 'Pb H ', 'AB', '0.042', '5.5', 'BTL', '1', '0.02', '2.3', '1000', 'Flip-Chip-12', '1', '260', '0.3239');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCV2820MUTBG', 'Active', 'Pb A H P ', 'D', '2.19', '5.5', 'Differential', '1', '0.05', '2.2', '300', 'DFN-8', '1', '260', '0.802');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2820FCT1G', 'Last Shipments', 'Pb H ', 'D', '2.12', '5.5', 'Differential', '9', '0.05', '2.2', '300', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2820MUTBG', 'Last Shipments', 'Pb H ', 'D', '2.19', '5.5', 'Differential', '1', '0.05', '2.2', '300', 'DFN-8', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2820FCT2G', 'Obsolete', 'Pb H ', 'D', '2.12', '5.5', 'Differential', '9', '0.05', '2.2', '300', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2820AFCT2G', 'Obsolete', 'Pb H ', 'D', '2.12', '5.5', 'Differential', '1', '0.05', '2.2', '300', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2823AFCT2G', 'Last Shipments', 'Pb H ', 'D', '1.5', '5.5', 'BTL', '7.4', '0.08', '1.8', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2823BFCT2G', 'Last Shipments', 'Pb H ', 'D', '3', '5.5', 'BTL', '7.4', '0.08', '2.6', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2823BFCT1G', 'Last Shipments', 'Pb H ', 'D', '3', '5.5', 'BTL', '7.4', '0.08', '2.6', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2823AFCCT2G', 'Last Shipments', 'Pb H ', 'D', '1.5', '5.5', 'BTL', '7.4', '0.08', '1.8', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2824FCT2G', 'Obsolete', 'Pb H ', 'D', '1.2', '5.5', 'BTL', '7.4', '0.06', '2.2', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2890DMR2G', 'Last Shipments', 'Pb H ', 'AB', '1', '5.5', 'BTL', '285', '0.02', '1.5', '10', 'Micro8', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2890AFCT2G', 'Obsolete', 'Pb H ', 'AB', '1', '5.5', 'BTL', '285', '0.02', '1.5', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2892AFCT2G', 'Obsolete', 'Pb H ', 'AB', '1.3', '5.5', 'BTL', '90', '0.01', '1.5', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2892BFCT2G', 'Obsolete', 'Pb H ', 'AB', '1.3', '5.5', 'BTL', '90', '0.01', '1.5', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2990FCT2G', 'Obsolete', 'Pb H ', 'AB', '1.3', '5.5', 'BTL', '70', '0.01', '1.7', '10', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2991FCT2G', 'Obsolete', 'Pb H ', 'AB', '1.35', '5.5', 'BTL', '30', '0.015', '1.8', '20', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP2993FCT2G', 'Obsolete', 'Pb H ', 'AB', '1.3', '5.5', 'BTL', '30', '0.015', '1.8', '20', 'Flip Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP4894FCT1G', 'Obsolete', 'Pb H ', 'AB', '1.8', '5.5', 'Differential', '140', '0.01', '1.9', '20', 'Flip-Chip-9', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP4894DMR2G', 'Obsolete', 'Pb H ', 'AB', '1.8', '5.5', 'Differential', '140', '0.01', '1.9', '20', 'Micro10', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCP4894MNR2G', 'Obsolete', 'Pb H ', 'AB', '1.8', '5.5', 'Differential', '140', '0.01', '1.9', '20', 'DFN-10', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCS2211MNTXG', 'Active', 'Pb H ', 'AB', '1.5', '5.5', 'BTL', '0.001', '0.2', '20', '1000', 'DFN-8', '1', '260', '0.3708');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCV2211DR2G', 'Active', 'Pb A H P ', 'AB', '1.5', '5.5', 'BTL', '0.001', '0.2', '20', '1000', 'SOIC-8', '1', '260', '0.3043');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCS2211DR2G', 'Active', 'Pb H ', 'AB', '1.5', '5.5', 'BTL', '0.001', '0.2', '20', '1000', 'SOIC-8', '1', '260', '0.2955');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCS2632DTBR2G', 'Active', 'Pb H ', 'AB', null, '5.5', 'Differential', '0.55', '0.001', '7', null, 'TSSOP-14', '1', '260', '0.382');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NCS8353MNTXG', 'Obsolete', 'Pb H ', 'D', '20', '26', 'BTL', '450', '0.03', '33', '0.1', 'QFN-32', '1', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NE570DR2G', 'Last Shipments', 'Pb H ', null, null, '24', null, null, null, null, null, 'SOIC-16W', '3', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NE570D', 'Obsolete', null, null, null, '24', null, null, null, null, null, 'SOIC-16W', '1', '235', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NE570DG', 'Obsolete', 'Pb H ', null, null, '24', null, null, null, null, null, 'SOIC-16W', '3', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('NE570DR2', 'Obsolete', null, null, null, '24', null, null, null, null, null, 'SOIC-16W', '1', '235', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571DR2G', 'Active', 'Pb H ', null, null, '18', null, null, null, null, null, 'SOIC-16W', '3', '260', '0.7168');
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571DR2', 'Obsolete', 'A P ', null, null, '18', null, null, null, null, null, 'SOIC-16W', '1', '235', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571DG', 'Obsolete', 'Pb H ', null, null, '18', null, null, null, null, null, 'SOIC-16W', '3', '260', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571NG', 'Obsolete', 'Pb A H P ', null, null, '18', null, null, null, null, null, 'PDIP-16', null, '0', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571N', 'Obsolete', 'A P ', null, null, '18', null, null, null, null, null, 'PDIP-16', null, '0', null);
INSERT INTO "AUDIO_AMPLIFIER" ("Product Group", "Status", "Compliance", "Class", "Output Power Typ (W)", "VCC Max (V)", "Output Type", "ton Typ (ms)", "THD + N Typ (%)", "IQ Typ (mA)", "ISD Typ (nA)", "Package Type", "MSL Type", "MSL Temp (°C)", "Pricing ($/Unit)") VALUES ('SA571D', 'Obsolete', 'A P ', null, null, '18', null, null, null, null, null, 'SOIC-16W', '1', '235', null);
